# -*- coding: utf-8 -*-
"""Colab: C24013 - Grupo 166 - TP P2 - Analítica auditoría CMM - Paraguay - Jun 2024

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15dC27r10111pj5UkXiHeXTz_sJZo4RMc
"""

# Acceso a Gsheets - Metodo con URL de conversion a CSV (lectura)
# El archivo debe tener permisos de lectura para TODOS

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
##################### Planilla de ventas ##########################
ID_planilla_ventas= '19hLeqEN91QSI6JxUXlTvPnFeMi8EU8esSIRNhpBn3ic'

URL_ventas = f'https://docs.google.com/spreadsheets/d/{ID_planilla_ventas}/gviz/tq?tqx=out:csv&sheet='


##################### Planilla de Distribuidores ##########################

ID_planilla_distribuidores= '1dYnRmsuwNt8hgvDyygWEh76ZD3gthIRObYU47knUuIo'

URL_distribuidores= f'https://docs.google.com/spreadsheets/d/{ID_planilla_distribuidores}/gviz/tq?tqx=out:csv&sheet='

##################### Planilla de Exportacion ##########################

ID_planilla_expotacion= '1NAVxrAsEZgdUeZti7j4hBVGDhjjkhvwTY1-Lg1EALzM'

URL_expotacion= f'https://docs.google.com/spreadsheets/d/{ID_planilla_expotacion}/gviz/tq?tqx=out:csv&sheet='



##################### Planilla de Localizacion ##########################

ID_planilla_localizacion= '1Dca7HB52JovJSMbX5ukF4JKmLXzxBszVUr40Fi3er1w'

URL_localizacion= f'https://docs.google.com/spreadsheets/d/{ID_planilla_localizacion}/gviz/tq?tqx=out:csv&sheet='

# CSV Ventas
df_Ventas= pd.read_csv(URL_ventas)
# EXPLORO LOS TIPOS DE DATOS
print (df_Ventas.dtypes)

#Renombro la columnas para luego poder hacer un merge a futuro
df_Ventas.rename(columns={'distributor':'Distribuidor'
,'Rubber':'Caucho'
,'Brass':'Laton'
,'Vinyl':'Vinilo'
,'Granite':'Granito'
,'Stone':'Piedra'
,'Brick':'Ladrillo'
,'Aluminum':'Aluminio'
,'Glass':'Vidrio'
,'Plexiglass':'Plexiglass'
,'Steel':'Acero'
,'Wood':'Madera'
,'Plastic':'Plastico'
}, inplace=True)

#COLUMNS NOS DESDE RUBBER HASTA LA ULTIMA COLUMNAS Y LUEGO AL LO CONVIERTO EN LISTA(con el list()) luego guardo esa lista en el campo columnas
columnas=list(df_Ventas.columns[1:13])
print (columnas)

#Elimino la Fila de Totales (Elimine la Fila 44 que contiene un string que contiene NaN)
df_Ventas.drop([44],inplace = True)
df_Ventas

#DISTRIBUTOR AL SER UNA COLUMNA TIPO FLOAT debo transformar la columna a TIPO INT
df_Ventas['Distribuidor']=df_Ventas['Distribuidor'].astype(int)
print (df_Ventas.dtypes)

#Reemplazo lo sig mediante un bucle for
#('$','') - Elimino los simbolo pesos y lo reemplazo por vacio
#('.','') - Elimino los simbolo puntos y lo reemplazo por vacio
#(',','.')- Elimino los simbolo coma y lo reemplazo por punto
#Esto me permite setear, para luego mas adelante poder realizar operaciones
for col in columnas:
 df_Ventas[col]=df_Ventas[col].replace({r'\$':'',r'\.':'',r',':'.'},regex=True)
#for col in columnas:
 #df_Ventas[col]=df_Ventas[col].str.replace(',','.')

#Ordeno de manera por Distribuidor de manera ascendente
df_Ventas.sort_values(by='Distribuidor', ascending=True)

#Reemplazo el typo de datos con un astype lo sig mediante un bucle for
for col in columnas:
 df_Ventas[col]=df_Ventas[col].astype(float)

#Visualizacion de Tabla mediante el DataFrame para Detección y eliminación de duplicados y/o filas/columnas inapropiadas o innecesarias
df_Ventas
pd.options.display.float_format = '{:.2f}'.format

#Visualizo que haya convertido las columnas a Float con un Dtype
df_Ventas.dtypes

df_Ventas

#Saco las metricas del df_Ventas
df_Ventas[columnas].describe()

#Saco la sumatoria de todas las columnas
df_Ventas[columnas].sum()

#Saco la sumatoria de todas las columnas y lo almaceno en una variable para luego poder graficar
total_sumasventas=df_Ventas[columnas].sum()
print(total_sumasventas)

df_Ventas

########################################################################################################################################


################################################################# EXPORTACION ##########################################################



########################################################################################################################################

# CSV Exportacion
df_Exportacion= pd.read_csv(URL_expotacion, thousands = '.')

# EXPLORO LOS TIPOS DE DATOS
print (df_Exportacion.dtypes)

#Renombro la columnas para luego poder hacer un merge a futuro
df_Exportacion.rename(columns={'distributor':'Distribuidor'
,'Rubber':'Caucho'
,'Brass':'Laton'
,'Vinyl':'Vinilo'
,'Granite':'Granito'
,'Stone':'Piedra'
,'Brick':'Ladrillo'
,'Aluminum':'Aluminio'
,'Glass':'Vidrio'
,'Plexiglass':'Plexiglass'
,'Steel':'Acero'
,'Wood':'Madera'
,'Plastic':'Plastico'
}, inplace=True)

#Imprimo para luego ver los datos
df_Exportacion

#Observamos la Columna 13, 14, y Columnas que no contienen datos y debemos eliminar
#Elimino con el DROPNA todas las columnas que contengan un dato NA (Elimine la columna unnamed y Columnas )
df_Exportacion.dropna(axis=1, inplace = True)
df_Exportacion

#Observo que los numeros de Distribuidor contienen punto, y de Rubber hasta la ultima columna Plastic tienen simbolos como "$", "." , "," que deben quedar correctos
#Reemplazo lo sig mediante un bucle for
#('$','') - Elimino los simbolo pesos y lo reemplazo por vacio
#('.','') - Elimino los simbolo puntos y lo reemplazo por vacio
#(',','.')- Elimino los simbolo coma y lo reemplazo por punto
#Esto me permite setear, para luego mas adelante poder realizar operaciones
for col in columnas:
 df_Exportacion[col]=df_Exportacion[col].str.replace('$','')
 df_Exportacion[col]=df_Exportacion[col].str.replace('.','')
for col in columnas:
 df_Exportacion[col]=df_Exportacion[col].str.replace(',','.')

#Verifico que no hayan datos duplicados y que me los sume (Me indica que la fila 19 se encuentra duplicada y la debo eliminar)
df_Exportacion.duplicated()

#Muestro los datos duplicados por Distribuidor
df_Exportacion[df_Exportacion['Distribuidor'].duplicated(keep=False)]

#Borro la fila 19 y 41 se encuentra duplicada
df_Exportacion=df_Exportacion.drop_duplicates()

#TENGO QUE CAMBIAR LAS COLUMNAS DE OBJETO A FLOTANTE PARA PODER REALIZAR OPERACIONES
#VISUALIZO EL TIPO DE FORMATO EN LAS COLUMNAS O VARIABLES QUE VAN DESDE RUBBER HASTA PLASTIC EN OBJECT
df_Exportacion.dtypes

#HAGO LA CONVERSION DE LAS COLUMNAS A FLOAT 0 A 9 Y DISTRIBUTOR LO TENGO QUE DEJAR COMO INT PARA PODER UNIRLO AL CSV VENTAS
for col in columnas:
  df_Exportacion[col]=df_Exportacion[col].astype(float)

df_Exportacion['Distribuidor']=df_Exportacion['Distribuidor'].astype(int)

#Ordeno el df.Exportacion por distribuidor de manera ascendente y fijo los cambios
df_Exportacion.sort_values(by='Distribuidor', ascending= True, inplace=True)

df_Exportacion

#Saco las metricas de Exportacion
df_Exportacion.describe()

#Saco los totales de Exportacion
df_Exportacion[columnas].sum()

#Grafico de Suma de Ventas
plt.title ("Total de Ventas por Material")
plt.xlabel("Material")
plt.ylabel("Importe Ventas")
series = pd.Series(total_sumasventas)
series.plot.bar()

#Totales de Exportacion lo almaceno en una variable
total_sumasexportacion=df_Exportacion[columnas].sum()
print (total_sumasexportacion)

plt.xlabel("Material")
plt.ylabel("Importe Ventas")
plt.title("Tabla de Importe de Materiales Exportados a Paraguay")
series = pd.Series(total_sumasexportacion)
series.plot.bar()

#Concateno la serie de total_sumasventas y total_sumasexportacion en una DataFrame union_frame
union_frame = pd.concat([total_sumasventas,total_sumasexportacion ], axis=1)

union_frame.rename(columns={0:'Ventas',1:'Exportacion'}, inplace=True)
union_frame

#Relizo mediante los graficos de data frame plot.bar() un grafico de barra que me muestre
union_frame.plot.bar()
plt.xlabel("Material")
plt.ylabel("Importe Ventas")
plt.title("Comparacion totales de Ventas y Exportacion por Productos")

#Sumo las columas de Todos los Productos
union_frame.sum()

#Almaceno el total de Ventas de productos y total de exportaciones
ventas_exportacion=union_frame.sum()
print (ventas_exportacion)

#Muestro el total de Ventas vs Exportacion mediante un grafico de torta el argumento autopct colocar los valores porcentuales dentro de cada grafico
#% saca el porcentaje de las variables y luego es el signo 1.1f lo convierte a decimal
ventas_exportacion['Ventas':'Exportacion'].plot.pie(autopct='%1.1f%%')

ventas_exportacion.plot.bar()
plt.xlabel("Totales")
plt.ylabel("Importes")
plt.title("Comparacion de Total ventas vs Total Exportacion")

########################################################################################################################################


################################################################# DISTRIBUIDORES ########################################################



########################################################################################################################################

# CSV Distribuidores
df_Distribuidores= pd.read_csv(URL_distribuidores)
# EXPLORO LOS TIPOS DE DATOS
print (df_Distribuidores.dtypes)

#IMPRIMO PARA VER QUE DATOS TENGO QUE BORRAR y SETEAR
df_Distribuidores

#Verifico que no hayan datos duplicados y que me los sume (Me indica que la fila 19 se encuentra duplicada y la debo eliminar)
df_Distribuidores.duplicated()

#Observamos la Columna 1, FILA 44 Y 45 son columnas que no tienen un dato NaN que esta duplicado
#Muestro los datos duplicados por ID
df_Distribuidores[df_Distribuidores['id'].duplicated(keep=False)]

#Elimino la fila 44 y 45 que no los datos estan duplicados y no contienen Informacion
df_Distribuidores.drop([44,45],inplace = True)

#Para dejar correctamente la columna ID hago un casteo los valores que son menor a 2 por ejemplo 1.500, los multiplico *1000 para luego poder quitarle el punto y que queden bien seteados
df_Distribuidores.loc[df_Distribuidores['id']<2,'id']*=1000
df_Distribuidores

#Cambio el TIPO DE COLUMNA ID QUE ESTA EN FLOAT A INT de la columna ID a INT
df_Distribuidores['id']=df_Distribuidores['id'].astype(int)
df_Distribuidores

#Elimino columnas innecesarias para el relevamiento de informacion
df_Distribuidores.drop(['distributor activities','years in the construction market'],axis=1, inplace = True)
df_Distribuidores

#Visualizo los nombres de las columnas
df_Distribuidores.columns

df_Distribuidores.rename(columns={'id':'Distribuidor','distributor':'Nombre Distribuidor'}, inplace=True)

df_Distribuidores

df_Distribuidores.dtypes

########################################################################################################################################


################################################################# LOCALIZACION ########################################################



########################################################################################################################################

# CSV Localizacion
df_Localizacion= pd.read_csv(URL_localizacion)
# EXPLORO LOS TIPOS DE DATOS
print (df_Localizacion.dtypes)

df_Localizacion

df_Localizacion.sort_values('PYid')

#Verifico que no hayan datos duplicados y que me los sume (Me indica que la fila 19 se encuentra duplicada y la debo eliminar)
df_Localizacion['id'].duplicated()

#Observamos la Columna 1, FILA 44 Y 45 son columnas que no tienen un dato NaN que esta duplicado
#Muestro los datos duplicados por ID
df_Localizacion[df_Localizacion['id'].duplicated(keep=False)]

#Elimino Todas las filas que no contienen datos
#axis=0 (filas) y axis=1(columnas)
df_Localizacion.dropna(axis=0, inplace = True)

df_Localizacion

df_Localizacion['id']=df_Localizacion['id'].astype(int)

df_Localizacion

#Distribuidores activos
df_Localizacion.rename(columns={'id':'Distribuidor'})

#Exploracion de datos
# Combino los df_ventas y df_distribuidores mediante la columna Distribuidor (inner join)
datos_ventas_distribuidores=pd.merge(df_Ventas, df_Distribuidores , how='inner',on='Distribuidor')
datos_ventas_distribuidores.rename(columns={'Rubber':'Caucho'
,'Brass':'Laton'
,'Vinyl':'Vinilo'
,'Granite':'Granito'
,'Stone':'Piedra'
,'Brick':'Ladrillo'
,'Aluminum':'Aluminio'
,'Glass':'Vidrio'
,'Plexiglass':'Plexiglass'
,'Steel':'Acero'
,'Wood':'Madera'
,'Plastic':'Plastico'
}, inplace=True)
datos_ventas_distribuidores.sort_values('Distribuidor', ascending=True, inplace= True)

datos_ventas_distribuidores

columnas=list(datos_ventas_distribuidores.columns)
columnas

#cambio el orden de nombre de distribuidor asi me queda al lado de distribuidor
columnas[1],columnas[13]=columnas[13],columnas[1]
columnas

#Exploracion de datos
# Combino los df_Exportacion y df_distribuidores mediante la columna Distribuidor (inner join)
datos_exportacion_distribuidores=pd.merge(df_Exportacion, df_Distribuidores , how='inner',on='Distribuidor')
datos_exportacion_distribuidores.rename(columns={'Rubber':'Caucho'
,'Brass':'Laton'
,'Vinyl':'Vinilo'
,'Granite':'Granito'
,'Stone':'Piedra'
,'Brick':'Ladrillo'
,'Aluminum':'Aluminio'
,'Glass':'Vidrio'
,'Plexiglass':'Plexiglass'
,'Steel':'Acero'
,'Wood':'Madera'
,'Plastic':'Plastico'
}, inplace=True)
datos_exportacion_distribuidores.sort_values('Distribuidor', ascending=True, inplace= True)

columnas=list(datos_exportacion_distribuidores.columns)
columnas

#cambio el orden de nombre de distribuidor asi me queda al lado de distribuidor
columnas[1],columnas[13]=columnas[13],columnas[1]
columnas

#Uno los dos merge o datos_ventas_distribuidores vs datos_exportacion_distribuidores
df_comun = datos_ventas_distribuidores.merge(datos_exportacion_distribuidores, on=['Distribuidor', 'Nombre Distribuidor'],how='inner')
df_comun.rename(columns={'Caucho_x':'Caucho_V','Caucho_y':'Caucho_E'
,'Laton_x':'Laton_V','Laton_y':'Laton_E'
,'Vinilo_x':'Vinilo_V','Vinilo_y':'Vinilo_E'
,'Granito_x':'Granito_V','Granito_y':'Granito_E'
,'Piedra_x':'Piedra_V','Piedra_y':'Piedra_E'
,'Ladrillo_x':'Ladrillo_V','Ladrillo_y':'Ladrillo_E'
,'Aluminio_x':'Aluminio_V','Aluminio_y':'Aluminio_E'
,'Vidrio_x':'Vidrio_V','Vidrio_y':'Vidrio_E'
,'Plexiglass_x':'Plexiglass_V','Plexiglass_y':'Plexiglass_E'
,'Acero_x':'Acero_V','Acero_y':'Acero_E'
,'Madera_x':'Madera_V','Madera_y':'Madera_E'
,'Plastico_x':'Plastico_V','Plastico_y':'Plastico_E'
}, inplace=True)
df_comun

df_comun.columns