--Permite ver que tipo de formato de fecha se esta utilizando en la sesión actualen oracle
SELECT * FROM NLS_SESSION_PARAMETERS WHERE PARAMETER = 'NLS_DATE_FORMAT';
--Cambiar el formato de fecha a MM/DD/YYYY
ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/YYYY';


-- Ver datos de cada tabla
SELECT 'EMPLOYEES' AS TABLA FROM DUAL
UNION ALL
SELECT 'JOBS' FROM DUAL
UNION ALL
SELECT 'DEPARTMENTS' FROM DUAL
UNION ALL
SELECT 'JOB_HISTORY' FROM DUAL;

-- Datos de EMPLOYEES
SELECT '--- EMPLOYEES ---' FROM DUAL;
SELECT * FROM EMPLOYEES;

-- Datos de JOBS
SELECT '--- JOBS ---' FROM DUAL;
SELECT * FROM JOBS;

-- Datos de DEPARTMENTS
SELECT '--- DEPARTMENTS ---' FROM DUAL;
SELECT * FROM DEPARTMENTS;

-- Datos de JOB_HISTORY
SELECT '--- JOB_HISTORY ---' FROM DUAL;
SELECT * FROM JOB_HISTORY;