-- Crear tablas en el nuevo esquema ANALISIS_DATOS y copiar los datos desde el esquema SYSTEM
CREATE TABLE ANALISIS_DATOS.DEPARTMENTS AS
SELECT * FROM SYSTEM.DEPARTMENTS;

CREATE TABLE ANALISIS_DATOS.JOBS AS
SELECT * FROM SYSTEM.JOBS;

CREATE TABLE ANALISIS_DATOS.JOB_HISTORY AS
SELECT * FROM SYSTEM.JOB_HISTORY;
--le doy permisos al nuevo esquema para que pueda acceder a las tablas
GRANT ALL PRIVILEGES ON ANALISIS_DATOS.LOCATIONS TO ANALISIS_DATOS;
GRANT ALL PRIVILEGES ON ANALISIS_DATOS.DEPARTMENTS TO ANALISIS_DATOS;
GRANT ALL PRIVILEGES ON ANALISIS_DATOS.EMPLOYEES TO ANALISIS_DATOS;
GRANT ALL PRIVILEGES ON ANALISIS_DATOS.JOBS TO ANALISIS_DATOS;
GRANT ALL PRIVILEGES ON ANALISIS_DATOS.JOB_HISTORY TO ANALISIS_DATOS;

--borrar tablas originales
DROP TABLE SYSTEM.DEPARTMENTS;
DROP TABLE SYSTEM.JOBS;
DROP TABLE SYSTEM.JOB_HISTORY;
DROP TABLE SYSTEM.EMPLOYEES;
DROP TABLE SYSTEM.LOCATIONS;